<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'product_name' => 'Chanel Blue de Chanel Eau De Parfum',
                'brand' => 'Chanel',
                'fragrance_type' => 'Woody Aromatic',
                'original_price' => 46000.00,
                'sale_price' => 45000.00,
                'stock_quantity' => 9,
                'category_id' => 2,
                'product_desc' => 'Unleash an aura of sophisticated masculinity with Chanel Bleu de Chanel Eau de Parfum, a fragrance that captures the essence of freedom and determination. This iconic scent, housed in a sleek deep blue bottle, is a timeless masterpiece for the man who carves his own path.',
                'size' => '100ml',
                'Bestseller' => 1,
                'gender' => 'F',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'La Vie Est Belle',
                'brand' => 'Lancôme',
                'fragrance_type' => 'Floral',
                'original_price' => 42000.00,
                'sale_price' => 41000.00,
                'stock_quantity' => 30,
                'category_id' => 2,
                'product_desc' => 'THE FRAGRANCE OF HAPPINESS. Life is what you make of it so make it beautiful with La vie est belle — the iconic women\'s fragrance by Lancôme. A floral gourmand bouquet encapsulated in a crystal smile. Blending the most noble ingredients, La vie est belle is an unforgettable fragrance. Precious Iris accord with vibrant earthy notes of patchouli, sensual warm vanilla and spun sugar are combined in this scent exclusively created by two of the most renowned French perfumers — Anne Flipo and Dominique Ropion. The art of French perfumery manifested in a unique bottle shape that symbolizes a smile. Each spray will unlock a beautiful day. "La vie est belle," a French expression meaning "life is beautiful," is about choosing your own path to happiness and inspiring others. - A TIMELESS AND ICONIC SCENT - OUR FIRST TASTY IRIS ACCORD - WITH SUSTAINABLY SOURCED INGREDIENTS* - A NEW REFILLABLE AND RECYCLABLE BOTTLE *Iris Pallida Concrete from France',
                'size' => '100ml',
                'Bestseller' => 1,
                'gender' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Add all other products here following the same format
            [
                'product_name' => 'Sauvage',
                'brand' => 'Dior',
                'fragrance_type' => 'Fresh Spicy',
                'original_price' => 48000.00,
                'sale_price' => 47000.00,
                'stock_quantity' => 24,
                'category_id' => 2,
                'product_desc' => 'Sauvage Parfum is a highly concentrated interpretation of Sauvage, melding extreme freshness with warm ambery tones and an animal beauty that begs to come alive on the skin. To compose Sauvage Parfum, Dior drew inspiration from a wild, unspoiled expanse beneath a blue-tinged night sky, as the intense odors of a crackling fire rise into the air. Its trail unfurls notes of mandarin, tonka bean and sandalwood. Sauvage Parfum is the fragrance of a new frontier, an interpretation with an enriched and intoxicating trail that celebrates the magic of wide-open spaces.',
                'size' => '100ml',
                'Bestseller' => 1,
                'gender' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Black Opium Eau De Parfum',
                'brand' => 'Yves Saint Laurent',
                'fragrance_type' => 'Oriental Vanilla',
                'original_price' => 43000.00,
                'sale_price' => 42000.00,
                'stock_quantity' => 25,
                'category_id' => 3,
                'product_desc' => 'Black Opium Eau de Parfum is the seductively intoxicating women\'s fragrance. The opening notes of adrenaline-rich coffee and the sweet sensuality of vanilla recline into the softness of white flowers creating a long-lasting perfume. This seductive women\'s perfume is inspired by the edgy and daring woman. Emboldened by the strong scent of coffee, the sensuous warm floral vanilla perfume captivates the senses with a sweet vanilla base and a burst of floral at the heart of the fragrance.',
                'size' => '90ml',
                'Bestseller' => 1,
                'gender' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Eros',
                'brand' => 'Versace',
                'fragrance_type' => 'Aromatic Fougere',
                'original_price' => 37000.00,
                'sale_price' => 36000.00,
                'stock_quantity' => 60,
                'category_id' => 3,
                'product_desc' => 'Masculine and confident, the Eros Parfum is a sensual fragrance that fuses woody, oriental and fresh notes, creating a powerful perfume that evokes Eros - the god of love. "I envisioned an heroic, passionate man, almost a Greek God. The fragrance is made up of notes that express sensuality and power, an extreme force," says Donatella Versace.',
                'size' => '100ml',
                'Bestseller' => 0,
                'gender' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Light Blue',
                'brand' => 'Dolce & Gabbana',
                'fragrance_type' => 'Citrus',
                'original_price' => 35000.00,
                'sale_price' => 34000.00,
                'stock_quantity' => 70,
                'category_id' => 5,
                'product_desc' => 'Light Blue by Dolce&Gabbana is a Floral Fruity fragrance for women. Light Blue was launched in 2001. The nose behind this fragrance is Olivier Cresp. Top notes are Sicilian Lemon, Apple, Cedar and Bellflower; middle notes are Bamboo, Jasmine and White Rose; base notes are Cedar, Musk and Amber.',
                'size' => '100ml',
                'Bestseller' => 0,
                'gender' => 'F',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Good Girl',
                'brand' => 'Carolina Herrera',
                'fragrance_type' => 'Oriental Floral',
                'original_price' => 40000.00,
                'sale_price' => 39000.00,
                'stock_quantity' => 35,
                'category_id' => 4,
                'product_desc' => 'GOOD GIRL is inspired by Carolina Herrera’s unique vision of the duality of the modern woman: audacious and sexy, elegant and enigmatic, good and bad. Forever pushing and crossing the limit, the mysterious sensuality of GOOD GIRL makes for a modern yet sophisticated fragrance.',
                'size' => '80ml',
                'Bestseller' => 1,
                'gender' => 'F',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Aventus',
                'brand' => 'Creed',
                'fragrance_type' => 'Fruity Chypre',
                'original_price' => 99000.00,
                'sale_price' => 97000.00,
                'stock_quantity' => 15,
                'category_id' => 1,
                'product_desc' => 'Audacious, confident and powerful, this signature fragrance from The House of Creed has been delicately crafted to create a true contemporary classic.',
                'size' => '100ml',
                'Bestseller' => 1,
                'gender' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'J’adore',
                'brand' => 'Dior',
                'fragrance_type' => 'Floral',
                'original_price' => 45000.00,
                'sale_price' => 44000.00,
                'stock_quantity' => 45,
                'category_id' => 2,
                'product_desc' => 'A rich floral scent.',
                'size' => '100ml',
                'Bestseller' => 0,
                'gender' => 'F',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Chanel NO. 5 Eau De Parfum',
                'brand' => 'Chanel',
                'fragrance_type' => 'Aldehydic Floral',
                'original_price' => 51000.00,
                'sale_price' => 50000.00,
                'stock_quantity' => 20,
                'category_id' => 2,
                'product_desc' => 'Chanel N°5 Since its creation in 1921, N°5 has exuded the very essence of femininity: An abstract, mysterious scent, alive with countless subtle facets, radiating an extravagant floral richness. In 1986, Jacques Polge, reinterpreted his predecessor Ernest Beaux’s composition to create a fuller, more voluminous version of the now and forever women’s fragrance: the Eau de Parfum...',
                'size' => '100ml',
                'Bestseller' => 1,
                'gender' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Oud Wood',
                'brand' => 'Tom Ford',
                'fragrance_type' => 'Woody Spicy',
                'original_price' => 72000.00,
                'sale_price' => 70000.00,
                'stock_quantity' => 10,
                'category_id' => 1,
                'product_desc' => 'With Oud Wood, TOM FORD uses rare oud notes to overwhelm the senses with dark, earthy sensuality. Exotic rosewood and cardamom give way to a smoky blend of precious oud notes, sandalwood and vetiver. Tonka bean and amber add warmth and sensuality.',
                'size' => '100ml',
                'Bestseller' => 1,
                'gender' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Gucci Flora Gorgeous Gardenia Eau De Parfum',
                'brand' => 'Gucci',
                'fragrance_type' => 'Floral',
                'original_price' => 43000.00,
                'sale_price' => 42000.00,
                'stock_quantity' => 30,
                'category_id' => 2,
                'product_desc' => 'Gucci is launching a special limited edition of Flora by Gucci perfume from 2009. It is named Flora by Gucci 1966, inspired by the “Flora” print that adorned the scarf designed for Grace Kelly. The perfume is launched in Spring 2013.',
                'size' => '100ml',
                'Bestseller' => 0,
                'gender' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => '1 Million',
                'brand' => 'Paco Rabanne',
                'fragrance_type' => 'Spicy Leather',
                'original_price' => 46000.00,
                'sale_price' => 45000.00,
                'stock_quantity' => 50,
                'category_id' => 6,
                'product_desc' => 'Love life’s danger, yet display your brilliance. Living is not about obeying all the rules. Just follow your dreams. One Million perfume: a beautiful, spicy leather fragrance for the most sassiest gentleman.',
                'size' => '100ml',
                'Bestseller' => 0,
                'gender' => 'F',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Le Male',
                'brand' => 'Jean Paul Gaultier',
                'fragrance_type' => 'Aromatic Fougere',
                'original_price' => 39000.00,
                'sale_price' => 38000.00,
                'stock_quantity' => 60,
                'category_id' => 6,
                'product_desc' => 'The latest men’s fragrance by Jean Paul Gaultier, Le Male Le Parfum, is about to set sail! Dressed in a black and gold officer’s jacket, this intense eau de parfum is taking leadership of the le male range with great style and strength. An elegant woody oriental trail capturing the charisma and power of a leader. Attention sailors! The captain has arrived and we’re about to set sail.',
                'size' => '100ml',
                'Bestseller' => 0,
                'gender' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Si',
                'brand' => 'Giorgio Armani',
                'fragrance_type' => 'Chypre Fruity',
                'original_price' => 44000.00,
                'sale_price' => 43000.00,
                'stock_quantity' => 25,
                'category_id' => 4,
                'product_desc' => 'Chic, voluptuous, intense, and soft - Si Eau di Parfum lingers on the skin encapsulating a distinguished and elegant fragrance, allowing those who wear it to express their every emotion. Sì has a top note of blackcurrant nectar, a heart of freesia and Rose of Mai, with a musky blond wood base. This rose fragrance was created for the modern woman who’s strong yet feminine, sophisticated yet charismatic. She embodies the very essence of chic Italian elegance and style.',
                'size' => '100ml',
                'Bestseller' => 0,
                'gender' => 'F',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}