<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductImagesTableSeeder extends Seeder
{
    public function run()
    {


        $images = [
            [
                'product_id' => 1,
                'image_path' => 'products/1/678a5b0ce73b0.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-05-28 21:37:35',
            ],
            [
                'product_id' => 1,
                'image_path' => 'products/1/featured.png',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-05-28 21:37:35',
            ],
            [
                'product_id' => 2,
                'image_path' => 'products/2/featured.png',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-05-28 21:37:35',
            ],
            [
                'product_id' => 2,
                'image_path' => 'products/2/678a5fdbb49f2.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-05-28 21:37:35',
            ],
            [
                'product_id' => 2,
                'image_path' => 'products/2/678a5fdbb5135.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-05-28 21:37:35',
            ],
            [
                'product_id' => 3,
                'image_path' => 'products/3/featured.png',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-05-28 21:37:35',
            ],
            [
                'product_id' => 3,
                'image_path' => 'products/3/678a5fe854989.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-05-28 21:37:35',
            ],
            [
                'product_id' => 4,
                'image_path' => 'products/4/featured.jpg',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 4,
                'image_path' => 'products/4/678a5ffb77275.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 4,
                'image_path' => 'products/4/678a5ffb77c46.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 5,
                'image_path' => 'products/5/featured.png',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 5,
                'image_path' => 'products/5/678a6006e7dc3.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 6,
                'image_path' => 'products/6/featured.png',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 6,
                'image_path' => 'products/6/678a6015ed879.png',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 7,
                'image_path' => 'products/7/featured.jpg',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 7,
                'image_path' => 'products/7/678a6025eff85.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 7,
                'image_path' => 'products/7/678a6025f0952.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 8,
                'image_path' => 'products/8/featured.jpg',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 8,
                'image_path' => 'products/8/678a6034620dc.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 9,
                'image_path' => 'products/9/featured.png',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 9,
                'image_path' => 'products/9/678a60431eec5.png',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 10,
                'image_path' => 'products/10/featured.png',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 10,
                'image_path' => 'products/10/678a60516fdf9.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 11,
                'image_path' => 'products/11/featured.png',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 11,
                'image_path' => 'products/11/678a605dc2e86.png',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 11,
                'image_path' => 'products/11/678a605dc3681.png',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 12,
                'image_path' => 'products/12/featured.jpg',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 12,
                'image_path' => 'products/12/678a60717298a.jpeg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 13,
                'image_path' => 'products/13/featured.jpg',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 13,
                'image_path' => 'products/13/678a6082d5964.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 13,
                'image_path' => 'products/13/678a6082d62d3.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 13,
                'image_path' => 'products/13/678a6082d6e88.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 13,
                'image_path' => 'products/13/678a6082d7a31.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 14,
                'image_path' => 'products/14/featured.jpg',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 14,
                'image_path' => 'products/14/678a609e79b2f.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 14,
                'image_path' => 'products/14/678a609e7a1f0.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 14,
                'image_path' => 'products/14/678a609e7a957.jpg',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 15,
                'image_path' => 'products/15/featured.jpg',
                'is_featured' => 1,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 15,
                'image_path' => 'products/15/678a60ad06b23.png',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
            [
                'product_id' => 15,
                'image_path' => 'products/15/678a60ad0733b.png',
                'is_featured' => 0,
                'alt_text' => null,
                'created_at' => '2025-06-02 05:22:16',
            ],
        ];

        DB::table('product_images')->insert($images);
    }
}